### ISSUE TITLE
Invalid argument: Error in DefineProperties

### ISSUE THREAD

**Issue by samardzicneo** [microsoft/node-api-dotnet#214]
Hello.

Unfortunately I'm facing an issue with your library when using `DefineProperties`:
```cs
o.DefineProperties(
            JSPropertyDescriptor.Accessor(
                "headersSent",
                _ => (JSValue)httpResponse.HasStarted,
                _ => JSValue.Undefined,
                JSPropertyAttributes.Default,
                false
            )
        );
```
```
nvite.NodeApi.JSException: Invalid argument: Error in DefineProperties at /Users/samaneo/RiderProjects/nvite/nvite.NodeApi/JSValue.cs:535
Error: Invalid argument: Error in DefineProperties at /Users/samaneo/RiderProjects/nvite/nvite.NodeApi/JSValue.cs:535
   at nvite.NodeApi.JSValue.<>c__DisplayClass108_0.<DefineProperties>b__0(String _, ReadOnlySpan`1 descriptorsPtr) in /Users/samaneo/RiderProjects/nvite/nvite.NodeApi/JSValue.cs:line 534
   at nvite.NodeApi.JSValue.ToUnmanagedPropertyDescriptors(String name, IReadOnlyCollection`1 descriptors, UseUnmanagedDescriptors action) in /Users/samaneo/RiderProjects/nvite/nvite.NodeApi/JSValue.cs:line 1610
   at nvite.NodeApi.JSValue.DefineProperties(JSPropertyDescriptor[] descriptors) in /Users/samaneo/RiderProjects/nvite/nvite.NodeApi/JSValue.cs:line 531
   at nvite.Library.Helpers.HttpHelpers.CreateServerResponse(JSValue incomingMessage, HttpResponse httpResponse) in /Users/samaneo/RiderProjects/nvite/nvite.Library/Helpers/HttpHelpers.cs:line 140
   at nvite.Library.Helpers.SsrInterop.<>c__DisplayClass6_0.<<HandlePath>b__0>d.MoveNext() in /Users/samaneo/RiderProjects/nvite/nvite.Library/Helpers/SsrInterop.cs:line 84
--- End of stack trace from previous location ---
   at nvite.Library.Helpers.SsrInterop.<>c__DisplayClass9_0`1.<<RunAsync>b__0>d.MoveNext() in /Users/samaneo/RiderProjects/nvite/nvite.Library/Helpers/SsrInterop.cs:line 128
```

As you can see I've changed the namespace but the code is still untouched, the only reason why I've moved your repo into my codebase is because I was getting assembly loading errors. I don't think this is relevant to the bug I'm seeing.

I'm using Node built from v21.x including the embedding patches, on a 2021 MacBook Pro.

Thanks in advance 👋🏼

**Comment by samardzicneo** [comment]
My bad - I think I was passing the wrong property attributes.

Using `JSPropertyAttributes.DefaultProperty` instead of `JSPropertyAttributes.Default` seems to fix the bug.
