### ISSUE TITLE
NotSupportedException : The invoked member is not supported before the type is created error

### ISSUE THREAD

**Issue by alexey-butalov-aspose** [microsoft/node-api-dotnet#233]
The error occurs for my real project. Unfortunately I couldn't create a sample project to reproduce it, also I can't share my project because of NDA.
```
CSC : error NAPI1001: NotSupportedException : The invoked member is not supported before the type is created.
   at System .Reflection.Emit.RuntimeTypeBuilder.GetConstructors(BindingFlags bindingAttr)
   at Microsoft.JavaScript.NodeApi.Generator.SymbolExtensions.AsConstructorInfo(IMethodSymbol methodSymbol)
   at Microsoft.JavaScript.NodeApi.Generator.ModuleGenerator.<>c.<ExportType>b__20_1(IMethodSymbol c)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at Microsoft.JavaScript.NodeApi.Generator.ModuleGenerator.ExportType(SourceBuilder& s, ITypeSymbol type, String exportName)
   at Microsoft.JavaScript.NodeApi.Generator.ModuleGenerator.ExportModule(SourceBuilder& s, ITypeSymbol moduleType, IEnumera ble`1 exportItems)
   at Microsoft.JavaScript.NodeApi.Generator.ModuleGenerator.GenerateModuleInitializer(ISymbol moduleIn itializer, IEnumerable`1 exportItems)
   at Microsoft.JavaScript.NodeApi.Generator.ModuleGenerator.Execute(GeneratorExecut ionContext context) 
```
0.5.12
```
dotnet publish -c DEBUG -r win-x64
```
AOT is enabled.
I have found #232 issue while trying to create a sample project to reproduce this issue.

**Comment by jasongin** [comment]
Thanks for the bug report. From the stack trace I have an idea of what might be going wrong here, so I can probably reproduce it with a little investigation time.

I suspect this is related to circular references between one of the types being exported and its base type. So you might be able to avoid the bug by avoiding export of that type, and ensuring any properties or methods that reference it are not exported or not public.

**Comment by alexey-butalov-aspose** [comment]
> Thanks for the bug report. From the stack trace I have an idea of what might be going wrong here, so I can probably reproduce it with a little investigation time.
> 
> I suspect this is related to circular references between one of the types being exported and its base type. So you might be able to avoid the bug by avoiding export of that type, and ensuring any properties or methods that reference it are not exported or not public.
I have marked only one top level complex class with JSExport attribute. I can update code to trace call tree or something else to help you in reproducing this issue.

**Comment by jasongin** [comment]
I can reproduce this error with the following code:

```C#
public class BaseClass
{
    protected BaseClass(int x) {}
    public DerivedClass Derived { get; set; }
}

[JSExport]
public class DerivedClass : BaseClass
{
    public DerivedClass(int x) : base(x) {}
}
```

I'm working on a fix.
