### ISSUE TITLE
Base interface is not processed yet while creating a derived interface type in BuildBaseTypeAndInterfaces() method

### ISSUE THREAD

**Issue by alexeybut** [microsoft/node-api-dotnet#244]
```
CSC : error NAPI1001: TypeLoadException : Could not load type 'ConsoleApp1.Int1' from assembly 'Microsoft.JavaScript.Node Api.Generator.SymbolExtensions_1, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.Emit.Run timeTypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.RuntimeTypeBuilder.CreateTypeInfoImpl()
   at Microsoft.JavaScript.NodeApi.Generator.SymbolExtensions.BuildBaseTypeAndInterfaces(INamedTypeSymbol typeSymbol)
   at Microsoft.JavaScript.NodeApi.Generator.SymbolExtensions.AsType(ITypeSymbol typeSymbol, Type[] genericTypeParameters, Boolean buildType)
   at Microsoft.JavaScript.NodeApi.Generator.SymbolExtensions.AsMethodInfo(IMethodSymbol methodSymbol)
   at Microsoft.JavaScript.NodeApi.Generator.ModuleGenerator.ExportMethod(SourceBuilder& s, IEnumerable`1 methods, String exportName)
   at Microsoft.JavaScript.NodeApi.Generator.ModuleGenerator.ExportMembers(SourceBuilder& s, ITypeSymbol type)
   at Microsoft.JavaScript.NodeApi.Generator.ModuleGenerator.ExportType(SourceBuilder& s, ITypeSymbol type, String exportName)
   at Microsoft.JavaScript.NodeApi.Generator.ModuleGenerator.ExportModule(SourceBuilder& s, ITypeSymbol moduleType, IEnumerable`1 exportI tems)
   at Microsoft.JavaScript.NodeApi.Generator.ModuleGenerator.GenerateModuleInitializer(ISymbol moduleInitializer, IE numerable`1 exportItems) [ConsoleApp1.csproj] 
```
Minimal code to reproduce:
```
    [JSExport]
    public class Class2
    {
        public string hello(Class1 a)
        {
            return "hello";
        }
    }

    public interface Int1
    {
    }

    public interface Int2 : Int1
    {
    }

    public class Class1 : Int2
    {
    }
```
NativeAOT is enabled.
Build command:
`
dotnet publish -c DEBUG -r win-x64
`
Sample project:
[ConsoleApp1.zip](https://github.com/microsoft/node-api-dotnet/files/14724604/ConsoleApp1.zip)

Version 0.5.18

**Comment by jasongin** [comment]
Fixed in 0.5.19.
